jobs:
  matchers: {
                "iou": {}
            }
  multiclass_strategy: [
        "all",
        "ignore_matched_undef",
        "ignore_unmatched_undef",
        "ignore_undef"
    ]
  binary_strategy: [
        "tn",
        "error",
        "ignore"
    ]
  event_map: {
        "1": 1,
        "2": 2,
        "3": 3,
        "4": 4,
        "5": 5,
        "0": 0
    }