data:
  data_dir: /home/martin/Documents/Exjobb/eed/.data/
  sklearn: true
  batch_size: 32
  validation_split: 0.2
  num_workers: 15
  window_size: 250
  print_extractionTime: false
  max_presaved_epochs: 99
  noise_levels:
  - 0
  - 0.1
  training_datasets:
  - no extra
pp_args:
  sacc_minimum_distance: 0.1
  pp_kwargs:
    thres_id: 75.0
    thres_ifa: 0.2
    thres_ifi: 75.0
    thres_sd_s: 3
    thres_pd: 3
    thres_isi: 25.0
    thres_sd_lo: 6.0
    thres_sd_hi: 150.0
    thres_fd: 50.0
jobs:
  matchers: {
                "iou": {}
            }
  multiclass_strategy: [
        "all",
        "ignore_matched_undef",
        "ignore_unmatched_undef",
        "ignore_undef"
    ]
  binary_strategy: [
        "tn",
        "error",
        "ignore"
    ]
  event_map: {
        "1": 1,
        "2": 2,
        "3": 1,
        "4": 1,
        "5": 5,
        "0": 0
    }
log_dir: /home/martin/Documents/Exjobb/eed/.experiments
study_name: TestSweep16
n_trials: 100
objective_metrics:
- IoU_mcc