data_module:
  class_path: ml.datasets.lookAtPointDatasetMiddleLabel.datamodule.LookAtPointDataMiddleLabelModule
  init_args:
    data_dir: /home/martin/Documents/Exjobb/eed/.data/
    sklearn: true
    validation_split: 0.2
    num_workers: 0
stage: fit
classifier_type: sklearn.ensemble.RandomForestClassifier
rf_config:
  n_trees: 38
  max_depth: 30
  class_weight: balanced_subsample
  max_features: 5
  n_jobs: 10
  verbose: 3
