data_module:
  class_path: ml.datasets.lookAtPointDatasetMiddleLabel.datamodule.LookAtPointDataMiddleLabelModule
  init_args:
    data_dir: /home/martin/Documents/Exjobb/eed/.data/
    sklearn: true
    validation_split: 0.2
    num_workers: 15
    window_size: 122
    window_size_vel: 237
    savgol_filter_window: 86
    noise_levels:
    - 0
    training_datasets:
    - SE_recorded
    - synthetic_data
stage: fit
classifier_type: sklearn.ensemble.RandomForestClassifier
rf_config:
  n_trees: 32
  max_depth: 2
  class_weight: balanced
  max_features: 4
  n_jobs: 15
  verbose: 3
pp_args:
  sacc_minimum_distance: 2
  pp_kwargs:
    thres_id: 75.0
    thres_ifa: 0.2
    thres_ifi: 75.0
    thres_sd_s: 3
    thres_pd: 3
    thres_isi: 25.0
    thres_sd_lo: 6.0
    thres_sd_hi: 600.0
    thres_fd: 50.0
event_map:
  '1': 1
  '2': 2
  '3': 1
  '4': 1
  '5': 5
  '0': 0