data_module:
  class_path: ml.datasets.lookAtPointDatasetNoWindow.datamodule.LookAtPointDataModuleNoWindow
  init_args:
    data_dir: /home/martin/Documents/Exjobb/eed/.data/
    sklearn: true
    validation_split: 0.2
    num_workers: 0
stage: fit
classifier_type: sklearn.ensemble.RandomForestClassifier
rf_config:
  n_trees: 100
  max_depth: null
  class_weight: balanced_subsample
  max_features: 3
  n_jobs: 1
  verbose: 3
